# Generated by Django 3.2.6 on 2021-08-06 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='voter',
            field=models.ManyToManyField(related_name='voter_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
